version: '3.7'
services:
  go-api:
    image: go-api:latest
    container_name: go-api
    ports:
      - 80:80

  api-mysql:
    image: mysql:8.0.28
    container_name: api-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=api
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql-db:/docker-entrypoint-initdb.d
      - ./storage/.db:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
